# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-24 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PurchaseRequisition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaserequisitionitem',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
